[tool.black]
line-length = 120
target-version = ['py39']
force-exclude = '''
/.(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
exclude = .git,__pycache__,build,dist