name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run Black
      run: black --check .
    
    - name: Run isort
      run: isort --check .
    
    - name: Run Flake8
      run: |
        flake8 src tests \
          --max-line-length=120 \
          --ignore=E203,E266,E501,W503 \
          --exclude=.git,__pycache__,build,dist