name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-clean:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    
    - name: Dry Run Black
      run: |
        black --check . || true
    
    - name: Manually Format Problematic Files
      run: |
        # List of files that need special handling
        problematic_files=(
          "src/ai_dev_workflow_trigger.py"
          "src/alerts/alert_manager.py"
          "src/assignment/team_manager.py"
          "src/collaboration_integrator.py"
          "src/config/settings.py"
          "src/dashboard/update_data.py"
          "src/database/models.py"
          "src/developer_skill_orchestrator.py"
          "src/integrations/dev_orchestrator.py"
          "src/main.py"
          "src/management/repo_manager.py"
          "src/master_project_orchestrator.py"
          "src/ml_task_allocator.py"
          "src/models/project_models.py"
          "src/monitoring/devops_monitor.py"
          "src/monitoring/issue_handler.py"
          "src/monitoring/monitor.py"
          "src/project_notification_system.py"
          "src/project_risk_predictor.py"
          "src/runners/analyze_blockchain.py"
          "src/runners/analyze_pos.py"
          "src/runners/analyze_ai.py"
          "src/services/project_service.py"
          "src/security_manager.py"
          "src/tools/devops_tools.py"
          "src/tools/technical_tools.py"
        )
        
        for file in "${problematic_files[@]}"; do
          if [ -f "$file" ]; then
            echo "Attempting to format $file"
            black --skip-string-normalization "$file" || true
          fi
        done
    
    - name: Sort Imports
      run: |
        isort .
    
    - name: Configure Git
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
    
    - name: Commit Changes
      run: |
        git add .
        git commit -m 'Automated code formatting and cleanup' || echo 'No changes to commit'
        git push