name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-clean:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autoflake isort black
    
    - name: Remove Unused Imports
      run: |
        find src tests -name "*.py" | xargs autoflake --in-place --remove-all-unused-imports
    
    - name: Sort Imports
      run: |
        isort .
    
    - name: Format Code
      run: |
        black .
    
    - name: Update Bare Except Blocks
      run: |
        # Script to replace bare except blocks
        for file in $(find src tests -name "*.py"); do
          sed -i 's/except:\s*pass/except Exception as e:\n    pass/g' $file
          sed -i 's/except:\s*continue/except Exception as e:\n    continue/g' $file
        done
    
    - name: Remove Unused Variables
      run: |
        # Basic removal of unused variables (simple approach)
        find src tests -name "*.py" -exec sed -i 's/^[[:space:]]*\([a-zA-Z_][a-zA-Z0-9_]*\)[[:space:]]*=[^=]*$/# \1/g' {} \;
    
    - name: Configure Git
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
    
    - name: Commit Changes
      run: |
        git add .
        git commit -m 'Automated code cleanup: remove unused imports, format code' || echo 'No changes to commit'
        git push