name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 pytest
    
    - name: Run Black formatter
      run: |
        black .
    
    - name: Run isort
      run: |
        isort .
    
    - name: Run Flake8
      run: |
        flake8 src tests
    
    - name: Configure Git
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
    
    - name: Commit formatting changes
      run: |
        git add .
        git commit -m 'Auto-format code with Black and isort' || echo 'No changes to commit'
        git push
    
    - name: Run Tests
      run: |
        pytest tests/