name: Docker Login Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker-login:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Verify Login
      run: |
        echo "Logged in successfully!"
        docker info
        echo "Docker version:"
        docker version
