name: Project Status Update

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update project status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python src/workflows/status_updater.py

    - name: Create status report
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add status/
        git commit -m "Update status reports" || echo "No changes to commit"
        git push