name: AI Task Allocator

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  allocate-tasks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub scikit-learn numpy
    
    - name: Run Task Allocator
      env:
        GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
      run: |
        python src/ml_task_allocator.py